version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
        name: install miniconda
        command: |
          export PATH="$HOME/miniconda/bin:$PATH"
          rm -rf ~/virtualenvs
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          hash -r
          conda config --add channels conda-forge
          conda config --set always_yes yes --set changeps1 no
          conda install --file requirements/tests.txt
          pip install xonda
      - run:
        name: tests
        command: |
          export PATH="$HOME/miniconda/bin:$PATH"
          git config --global user.name "Anthony Scopatz"
          git config --global user.email scopatz@gmail.com
          pytest -v ./tests/

workflows:
  version: 2
  run_all:
    jobs:
      - build
